(()=>{'use strict';
const root=document.documentElement,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],clamp=(n,a=0,b=1)=>Math.min(b,Math.max(a,n));
const reduce=matchMedia('(prefers-reduced-motion: reduce)'),fine=matchMedia('(hover: hover) and (pointer: fine)');
let requestedNav="",smooth=null,frame=0,lastFocus=null,currentPhoto=0,dialogBusy=false,closing=false,toastTimer=0;
const photos=[{"src":"assets/photos/alpine-light.webp","name":"日照金山","caption":"日照金山"},{"src":"assets/photos/sunset-bridge.webp","name":"落日大桥","caption":"落日大桥"},{"src":"assets/second-world/06-full.webp","name":"晚霞盖下来","caption":"第二世界 · 晚霞盖下来"},{"src":"assets/second-world/09-full.webp","name":"花荫正好","caption":"第二世界 · 花荫正好"},{"src":"assets/second-world/01-full.webp","name":"在云边歇一会","caption":"第二世界 · 在云边歇一会"}];
function initScroll(){smooth?.destroy();smooth=!reduce.matches&&typeof Lenis==='function'?new Lenis({autoRaf:true,lerp:.115,smoothWheel:true,syncTouch:false,anchors:false,prevent:el=>!!el.closest?.('dialog')}):null}
initScroll();
const menu=$('.menu-button'),nav=$('#main-nav');
function closeMenu(){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','打开导航')}
menu.addEventListener('click',()=>{const state=!nav.classList.contains('open');nav.classList.toggle('open',state);menu.setAttribute('aria-expanded',String(state));menu.setAttribute('aria-label',state?'关闭导航':'打开导航')});
document.addEventListener('click',e=>{if(!e.target.closest('.site-header'))closeMenu()});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&nav.classList.contains('open')){closeMenu();menu.focus()}});
function navigate(target,hash){for(let parent=target.parentElement.closest('details');parent;parent=parent.parentElement.closest('details'))parent.open=true;requestedNav=target.id==='photography'||target.matches('[data-photo]')?'photography':target.closest('section[id]')?.id||target.id;closeMenu();if(target.matches('[data-photo]'))selectPhoto(Number(target.dataset.photo));if(target.matches('.practice-entry')&&!target.open)target.open=true;const offset=innerWidth<=760?95:115;const destination=Math.max(0,target.getBoundingClientRect().top+scrollY-offset);if(smooth)smooth.scrollTo(destination,{duration:1.05});else scrollTo({top:destination,behavior:reduce.matches?'instant':'smooth'});if(hash)history.pushState(null,'',hash);const focusTarget=target.matches('section')?target.querySelector('h2,h1'):target.matches('details')?target.querySelector('summary'):null;if(focusTarget){focusTarget.tabIndex=-1;focusTarget.focus({preventScroll:true})}schedule()}
document.addEventListener('click',e=>{const link=e.target.closest('a[href^="#"]');if(!link)return;const target=document.getElementById(link.hash.slice(1));if(!target)return;e.preventDefault();navigate(target,link.hash)});
const skyButtons=$$('[data-sky-choice]'),thumb=$('.sky-thumb'),themes=['day','dusk','night'];let skyAnimation=null;
function positionSky(mode,animate=true){const button=skyButtons.find(b=>b.dataset.skyChoice===mode),left=button.offsetLeft,width=button.offsetWidth;const oldLeft=parseFloat(thumb.style.left)||4,oldWidth=parseFloat(thumb.style.width)||width;skyAnimation?.cancel();thumb.style.left=left+'px';thumb.style.width=width+'px';if(animate&&!reduce.matches&&Math.abs(oldLeft-left)>1){const forward=left>oldLeft;const stretchLeft=Math.min(left,oldLeft),stretchWidth=Math.max(left+width,oldLeft+oldWidth)-stretchLeft;skyAnimation=thumb.animate([{left:oldLeft+'px',width:oldWidth+'px',offset:0},{left:stretchLeft+'px',width:stretchWidth+'px',offset:.22},{left:(left+(forward?2:-2))+'px',width:(width-2)+'px',offset:.57},{left:(left+(forward?-1:1))+'px',width:(width+1)+'px',offset:.78},{left:left+'px',width:width+'px',offset:1}],{duration:850,easing:'cubic-bezier(.2,.7,.25,1)'})}}
function setSky(mode,{animate=true,save=true}={}){if(!themes.includes(mode))mode='day';root.dataset.sky=mode;skyButtons.forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.skyChoice===mode)));positionSky(mode,animate);$('meta[name="theme-color"]').content={day:'#34658a',dusk:'#50567b',night:'#17243e'}[mode];if(save)try{localStorage.setItem('mrnice-sky',mode)}catch{}}
let initialSky;try{initialSky=localStorage.getItem('mrnice-sky')}catch{}if(!themes.includes(initialSky)){const hour=Number(new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Shanghai',hour:'2-digit',hour12:false}).format(new Date));initialSky=hour>=7&&hour<17?'day':hour>=17&&hour<20?'dusk':'night'}
setSky(initialSky,{animate:false,save:false});
skyButtons.forEach((b,i)=>{b.addEventListener('click',()=>setSky(b.dataset.skyChoice));b.addEventListener('keydown',e=>{let next;if(e.key==='ArrowRight')next=(i+1)%3;else if(e.key==='ArrowLeft')next=(i+2)%3;else return;e.preventDefault();skyButtons[next].focus();setSky(themes[next])})});
const tiles=$$('[data-photo]');
function selectPhoto(index,{focus=false}={}){
 currentPhoto=(index+photos.length)%photos.length;
 if(!focus)return;
 const tile=tiles[currentPhoto];tile.focus({preventScroll:true});
 const rail=tile.closest('.photograph-series');
 if(rail&&rail.scrollWidth>rail.clientWidth){const left=rail.scrollLeft+tile.getBoundingClientRect().left-rail.getBoundingClientRect().left;rail.scrollTo({left,behavior:reduce.matches?'instant':'smooth'})}
}
tiles.forEach((button,i)=>{button.addEventListener('click',()=>openPhoto(i,button));button.addEventListener('keydown',e=>{let index;if(e.key==='ArrowRight')index=i+1;else if(e.key==='ArrowLeft')index=i-1;else if(e.key==='Home')index=0;else if(e.key==='End')index=photos.length-1;else return;e.preventDefault();selectPhoto(index,{focus:true})})});
const dialog=$('#photo-dialog'),dialogImage=$('#dialog-image');let activeImageAnimation=null,photoToken=0,viewerIndex=0,activeCollection=photos;
const worldPhotos=[{src:'assets/second-world/06-full.webp',name:'晚霞盖下来',caption:'第二世界 · 晚霞盖下来'},{src:'assets/second-world/09-full.webp',name:'花荫正好',caption:'第二世界 · 花荫正好'},{src:'assets/second-world/01-full.webp',name:'在云边歇一会',caption:'第二世界 · 在云边歇一会'}];
function dialogContent(){const p=activeCollection[viewerIndex];dialogImage.src=p.src;dialogImage.alt=p.caption;$('#dialog-caption').textContent=p.caption;$('.dialog-count').textContent=`${String(viewerIndex+1).padStart(2,'0')} / ${String(activeCollection.length).padStart(2,'0')}`}
async function openPhoto(index,button,collection=photos){if(dialog.open||dialogBusy)return;dialogBusy=true;const token=++photoToken;lastFocus=button;activeCollection=collection;viewerIndex=index;if(collection===photos)selectPhoto(index);dialogContent();try{await dialogImage.decode()}catch{}if(token!==photoToken){dialogBusy=false;return}dialog.showModal();smooth?.stop();document.body.style.overflow='hidden';$('.dialog-close').focus();if(!reduce.matches){const box=button.getBoundingClientRect(),imageBox=dialogImage.getBoundingClientRect();activeImageAnimation=dialogImage.animate([{opacity:.1,transform:`translate(${box.left+box.width/2-imageBox.left-imageBox.width/2}px,${box.top+box.height/2-imageBox.top-imageBox.height/2}px) scale(.65)`},{opacity:1,transform:'none'}],{duration:520,easing:'cubic-bezier(.16,1,.3,1)'});try{await activeImageAnimation.finished}catch{}}dialogBusy=false}
async function closePhoto(){if(!dialog.open||closing)return;closing=true;++photoToken;activeImageAnimation?.cancel();dialogBusy=false;if(!reduce.matches){const exit=dialog.animate([{opacity:1},{opacity:0}],{duration:230,easing:'ease-in',fill:'both'});try{await exit.finished}catch{}dialog.close();exit.cancel()}else dialog.close();closing=false}
dialog.addEventListener('close',()=>{document.body.style.overflow='';smooth?.start();lastFocus?.focus({preventScroll:true});schedule()});dialog.addEventListener('cancel',e=>{e.preventDefault();closePhoto()});$('.dialog-close').addEventListener('click',closePhoto);dialog.addEventListener('click',e=>{if(e.target===dialog)closePhoto()});
async function cyclePhoto(direction){if(!dialog.open)return;const token=++photoToken;activeImageAnimation?.cancel();viewerIndex=(viewerIndex+direction+activeCollection.length)%activeCollection.length;if(activeCollection===photos)selectPhoto(viewerIndex);dialogContent();try{await dialogImage.decode()}catch{}if(token!==photoToken||!dialog.open)return;if(!reduce.matches)dialogImage.animate([{opacity:.45,transform:`translateX(${direction*12}px)`},{opacity:1,transform:'none'}],{duration:300,easing:'ease-out'})}
$('.photo-prev').addEventListener('click',()=>cyclePhoto(-1));$('.photo-next').addEventListener('click',()=>cyclePhoto(1));dialog.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();cyclePhoto(e.key==='ArrowLeft'?-1:1)}});
function toast(message){const el=$('.toast');clearTimeout(toastTimer);el.textContent=message;el.classList.add('show');toastTimer=setTimeout(()=>el.classList.remove('show'),2500)}
$('#copy-email').addEventListener('click',async()=>{try{await navigator.clipboard.writeText('2503668375@qq.com');toast('邮箱已复制')}catch{toast('请长按或选中邮箱地址复制')}});
$$('[data-world]').forEach(button=>button.addEventListener('click',()=>openPhoto(Number(button.dataset.world),button,worldPhotos)));
const projectDialog=$('#project-dialog'),projectBody=$('#project-dialog-body');let projectTrigger=null,projectClosing=false;
function openProject(key,button){const template=document.getElementById('details-'+key);if(!template||projectDialog.open)return;projectTrigger=button;$('#project-dialog-title').textContent=template.dataset.title;projectBody.replaceChildren(template.content.cloneNode(true));projectDialog.showModal();smooth?.stop();document.body.style.overflow='hidden';$('.project-dialog-close').focus();if(!reduce.matches)projectDialog.animate([{opacity:0,transform:'translateY(12px) scale(.985)'},{opacity:1,transform:'none'}],{duration:260,easing:'cubic-bezier(.16,1,.3,1)'})}
async function closeProject(){if(!projectDialog.open||projectClosing)return;projectClosing=true;if(!reduce.matches){const animation=projectDialog.animate([{opacity:1},{opacity:0}],{duration:180,easing:'ease-in',fill:'both'});try{await animation.finished}catch{}projectDialog.close();animation.cancel()}else projectDialog.close();projectClosing=false}
$$('[data-project]').forEach(button=>button.addEventListener('click',()=>openProject(button.dataset.project,button)));
$('.project-dialog-close').addEventListener('click',closeProject);projectDialog.addEventListener('cancel',e=>{e.preventDefault();closeProject()});projectDialog.addEventListener('click',e=>{if(e.target===projectDialog){const r=projectDialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeProject()}});projectDialog.addEventListener('close',()=>{document.body.style.overflow='';smooth?.start();projectTrigger?.focus({preventScroll:true});schedule()});
document.addEventListener('click',async e=>{const copyButton=e.target.closest('#copy-world-prompt');if(!copyButton)return;const prompt='请完整读取我上传的「第二世界摄影二创」指南，作为本次对话的创作参考。先读图，让照片中的云、水、枝条或光沿着原来的结构进入纸面，与极简手绘人物自然互动。读完后等我上传照片；如果无法读取或生图，请直接说明。';try{await navigator.clipboard.writeText(prompt);copyButton.textContent='使用提示已复制 ✓';copyButton.setAttribute('aria-live','polite');setTimeout(()=>{if(copyButton.isConnected)copyButton.textContent='复制使用提示'},2400)}catch{copyButton.textContent='请下载创作指南后使用'}});
const assembly=$('.assembly'),board=$('.board'),cards=$$('[data-arrive]');let layout=[],staged=false;
function measure(){assembly.style.setProperty('--board-height',`${board.offsetHeight}px`);staged=false;assembly.classList.remove('is-staged');layout=['about','work','photography','contact'].map(id=>{const el=document.getElementById(id);return {id,el}});positionSky(root.dataset.sky,false);smooth?.resize();schedule()}
function schedule(){if(!frame&&!document.hidden)frame=requestAnimationFrame(draw)}
function draw(){frame=0;const h=innerHeight,y=scrollY,rect=assembly.getBoundingClientRect();root.classList.toggle('has-scrolled',y>120);root.classList.toggle('past-hero',y>h-220);root.style.setProperty('--hero-y',`${-Math.min(y,h)*.11}px`);root.style.setProperty('--hero-opacity',String(clamp(1-y/h*.88)));$('.reading-progress').style.setProperty('--progress',clamp(y/Math.max(1,root.scrollHeight-h)));
const base=clamp((h*.75-rect.top)/(h*.8));cards.forEach(card=>{if(reduce.matches||innerWidth<=1100){card.style.removeProperty('--arrive-y');card.style.removeProperty('--arrive-opacity');return}const delay=Number(card.dataset.arrive),p=clamp((base-delay*.45)/.64),ease=1-(1-p)**3;card.style.setProperty('--arrive-y',`${(1-ease)*(80+delay*130)}px`);card.style.setProperty('--arrive-opacity',String(.16+ease*.84))});
let active='';for(const item of layout){if(item.el.getBoundingClientRect().top<Math.max(180,h*.25))active=item.id}if(y<100)active='';const links=[...nav.querySelectorAll('a')];let current;links.forEach(a=>{const yes=a.hash===`#${active}`;if(yes){a.setAttribute('aria-current','location');current=a}else a.removeAttribute('aria-current')});nav.classList.toggle('has-active',!!current);if(current){$('.nav-indicator').style.width=current.offsetWidth+'px';$('.nav-indicator').style.setProperty('--nav-x',`${current.offsetLeft-5}px`)}}
$$('.glass').forEach(card=>{let pointerFrame=0,pending=null;card.addEventListener('pointermove',e=>{if(!fine.matches||reduce.matches||e.pointerType==='touch')return;pending={x:e.clientX,y:e.clientY};if(pointerFrame)return;pointerFrame=requestAnimationFrame(()=>{pointerFrame=0;const box=card.getBoundingClientRect(),dx=(pending.x-box.left)/box.width-.5,dy=(pending.y-box.top)/box.height-.5;card.style.setProperty('--light-angle',`${135+dx*90+dy*30}deg`);card.style.setProperty('--edge-light','.85');if(card.classList.contains('board-item')){card.style.setProperty('--pull-x',`${dx*3}px`);card.style.setProperty('--pull-y',`${dy*3}px`)}})});card.addEventListener('pointerleave',()=>{cancelAnimationFrame(pointerFrame);pointerFrame=0;card.style.removeProperty('--pull-x');card.style.removeProperty('--pull-y');card.style.removeProperty('--edge-light');card.style.removeProperty('--light-angle')})});
addEventListener('wheel',()=>{requestedNav=''}, {passive:true});addEventListener('touchstart',()=>{requestedNav=''}, {passive:true});addEventListener('scroll',schedule,{passive:true});addEventListener('resize',measure,{passive:true});document.fonts.ready.then(measure);$$('img').forEach(img=>img.addEventListener('load',measure,{once:true}));reduce.addEventListener('change',()=>{initScroll();measure()});document.addEventListener('visibilitychange',()=>{if(!document.hidden){measure()}});
selectPhoto(0);measure();if(!reduce.matches){$$('.hero-kicker,.hero h1,.hero-description,.hero-project-link,.hero-bottom').forEach((el,i)=>el.animate([{opacity:0,transform:'translateY(15px)'},{opacity:1,transform:'none'}],{duration:950,delay:100+i*110,easing:'cubic-bezier(.16,1,.3,1)',fill:'backwards'}))}
// Reset on page entry and browser restoration; in-page navigation remains available.
addEventListener('pageshow',()=>{if(location.hash)history.replaceState(null,'',location.pathname+location.search);requestedNav='';closeMenu();smooth?.scrollTo(0,{immediate:true,force:true});scrollTo({top:0,left:0,behavior:'instant'});schedule()});
})();
